sudo: false
os:
  - linux
language: r
assert: false
r: bioc-devel
bioc_required: true
r_packages:
 - knitr
 - rmarkdown
 - testthat
 - pander
 - XML
 - assertthat
 - stringi
 - rvest
 - data.table
 - magrittr
 - xml2
 - devtools
 - dplyr
 - survival
 - ggplot2
 - tidyr
 - ggthemes
 - purrr
 - viridis
 - scales
 - survminer
bioc_packages:
 - RTCGA.rnaseq
 - RTCGA.clinical
 - RTCGA.mutations
 - RTCGA.CNV
 - RTCGA.PANCAN12
 - RTCGA.RPPA
 - RTCGA.mRNA
 - RTCGA.miRNASeq
 - RTCGA.methylation
 - Biobase
 - GenomicRanges
 - IRanges
 - S4Vectors
 - BiocCheck
 
install:
- R -e "BiocManager::install(version = '3.12')"

after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"